"""Protocol A1: prompt-randomized self-consistency.

Each cell is one ``(benchmark, model)`` combination. For a fixed model, the
ensemble is generated by drawing ``K`` self-consistency samples per instance,
where sample ``k`` uses the prompt variation ``k mod K_var`` (``K_var`` is the
number of deterministic surface-form variations exposed by
:mod:`src.llm.prompts`, currently 16). Surface-form randomization is therefore
the *only* source of ensemble diversity in this protocol; the underlying model
and decoding parameters are held fixed across the ``K`` samples.

Determinism: the per-``(instance, k)`` generation seed is derived via
``derive_seed(seed, benchmark, model, instance_id, k, "gen")`` and forwarded to
the vLLM sampler, so the entire run is reproducible across machines. The same
integer also selects the prompt variation, keeping prompt choice and decoding
seed coupled and reproducible.

Pool semantics: this function writes records for a SINGLE pool (``estimation``
or ``oracle``); the two pools are disjoint at the instance level (see
:mod:`src.protocols.pools`). The oracle pool only ever feeds the R_N^MC
reference and never certificate construction.

No silent skips: an invalid parse is *kept* as a record with
``invalid_parse=True``, ``success_indicator=0`` and the raw completion
preserved (invalid-parse-is-failure bridge lemma). Generation is served
exclusively by a live vLLM server through :class:`src.llm.vllm_client.VLLMClient`
(constructed lazily from ``cell_config`` if not supplied); the heavy
``openai``/``vllm`` dependencies are imported lazily inside method bodies, so
this module imports cleanly in Phase 0 where they are unavailable. The function
body that performs generation only runs when invoked with a live client.
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Any, Literal

from src.llm.extraction import extract_answer
from src.llm.labeling import label
from src.llm.prompts import NUM_VARIATIONS, format_prompt
from src.utils.logging import JsonlLogger
from src.utils.schema import PanelARecord, validate_records
from src.utils.seeds import derive_seed


def _build_client(cell_config: dict, model: str) -> Any:
    """Return a live generation client.

    Prefers an explicit client passed under ``cell_config["client"]`` (used by
    the orchestrator that already holds an open vLLM connection). Otherwise
    constructs a :class:`VLLMClient` from ``cell_config["base_url"]`` /
    ``cell_config["api_key"]``. The ``VLLMClient`` import is local so that this
    module stays importable without the ``openai`` package installed.
    """
    client = cell_config.get("client")
    if client is not None:
        return client
    base_url = cell_config.get("base_url")
    if base_url is None:
        raise ValueError(
            "cell_config must provide a live 'client' or a 'base_url' for "
            "constructing a VLLMClient; no silent fallback is permitted"
        )
    from src.llm.vllm_client import VLLMClient  # lazy: avoids openai at import

    return VLLMClient(
        base_url=base_url,
        api_key=cell_config.get("api_key", "EMPTY"),
        model=cell_config.get("served_model_name", model),
    )


def _instance_index(instance_ids: list[str]) -> dict[str, int]:
    """Map each instance id to its row index ``m`` (stable, 0-based)."""
    if len(set(instance_ids)) != len(instance_ids):
        raise ValueError("instance_ids must be unique")
    return {iid: m for m, iid in enumerate(instance_ids)}


def run_protocol_a1(
    benchmark: str,
    model: str,
    instance_ids: list[str],
    K: int,
    pool_type: Literal["estimation", "oracle"],
    cell_config: dict,
    out_path: Path,
    seed: int,
) -> None:
    """Run Protocol A1 for one ``(benchmark, model)`` cell and one pool.

    Generates ``K`` prompt-randomized self-consistency samples for every
    instance, labels them, validates the per-sample records against
    :class:`PanelARecord`, and writes one JSONL line per ``(m, k)`` to
    ``out_path``.

    Parameters
    ----------
    benchmark:
        One of ``"arc_challenge"``, ``"gsm8k"``, ``"mmlu_subset"``.
    model:
        Model name (also used in the deterministic seed key and stored on each
        record).
    instance_ids:
        Ordered, unique instance ids for this pool; their position defines the
        row index ``m``.
    K:
        Number of self-consistency samples per instance (``K_full`` for the
        estimation pool, ``K_ref`` for the oracle pool).
    pool_type:
        ``"estimation"`` or ``"oracle"``. Written verbatim to each record's
        ``pool`` field; the oracle pool never feeds certificate construction.
    cell_config:
        Run configuration. Must supply the items dict
        (``cell_config["items"]`` mapping instance_id -> instance dict) and a
        generation client (``cell_config["client"]``) or ``base_url`` to build
        one, plus decoding params ``temperature``, ``top_p``, ``max_tokens``.
    out_path:
        Destination JSONL file (one validated record per line).
    seed:
        Global seed; per-``(instance, k)`` seeds are derived from it.

    Raises
    ------
    ValueError
        On unknown benchmark, duplicate/missing instances, or invalid config.
    RuntimeError
        On any generation failure (propagated from the client; no fallback).
    """
    if benchmark not in ("arc_challenge", "gsm8k", "mmlu_subset"):
        raise ValueError(f"unknown benchmark: {benchmark}")
    if pool_type not in ("estimation", "oracle"):
        raise ValueError(f"pool_type must be 'estimation' or 'oracle', got {pool_type}")
    if K < 1:
        raise ValueError(f"K must be >= 1, got {K}")

    items: dict[str, dict] = cell_config.get("items") or {}
    if not items:
        raise ValueError("cell_config['items'] must map instance_id -> instance dict")

    temperature = float(cell_config.get("temperature", 0.7))
    top_p = float(cell_config.get("top_p", 0.95))
    max_tokens = int(cell_config.get("max_tokens", 512))

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    logger = JsonlLogger(cell_config.get("log_path", out_path.parent / "protocol_a1.jsonl"))
    extract_log = cell_config.get("extraction_log_path")

    row_of = _instance_index(instance_ids)
    client = _build_client(cell_config, model)

    logger.event(
        "protocol_a1.start",
        benchmark=benchmark,
        model=model,
        pool=pool_type,
        n_instances=len(instance_ids),
        K=K,
        K_var=NUM_VARIATIONS,
        out_path=str(out_path),
    )

    with out_path.open("w", encoding="utf-8") as fh:
        for instance_id in instance_ids:
            m = row_of[instance_id]
            item = items.get(instance_id)
            if item is None:
                raise ValueError(f"no item dict supplied for instance_id={instance_id!r}")
            gold = item["gold_answer"]

            for k in range(K):
                gen_seed = derive_seed(seed, benchmark, model, instance_id, k, "gen")
                # Sample-k uses prompt variation k mod K_var. We pass a
                # variation-selecting seed whose residue mod NUM_VARIATIONS is
                # exactly (k mod K_var) so the formatter picks variation k.
                prompt, variation_id = format_prompt(item, benchmark, k % NUM_VARIATIONS)

                t0 = time.time()
                completions = client.generate(
                    prompt=prompt,
                    n_samples=1,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    seed=gen_seed,
                    top_p=top_p,
                )
                latency_ms = (time.time() - t0) * 1000.0
                raw_completion = completions[0] if completions else ""

                extracted, invalid_parse = extract_answer(
                    raw_completion,
                    benchmark,
                    log_path=extract_log,
                    instance_id=instance_id,
                )
                # invalid-parse-is-failure: keep the row, force success 0.
                success = 0 if invalid_parse else int(label(extracted, gold, benchmark))

                record = {
                    "instance_id": instance_id,
                    "pool": pool_type,
                    "m": m,
                    "k": k,
                    "prompt_variation_id": variation_id,
                    "prompt": prompt,
                    "raw_completion": raw_completion,
                    "extracted_answer": extracted,
                    "gold_answer": str(gold),
                    "success_indicator": success,
                    "invalid_parse": bool(invalid_parse),
                    "model": model,
                    "latency_ms": latency_ms,
                    "seed": gen_seed,
                }
                (validated,) = validate_records([record], PanelARecord)
                import json

                fh.write(json.dumps(validated, default=str) + "\n")

    logger.event(
        "protocol_a1.done",
        benchmark=benchmark,
        model=model,
        pool=pool_type,
        n_records=len(instance_ids) * K,
        out_path=str(out_path),
    )
